name: Build & Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build solution
        run: msbuild cs2-external-esp.sln /p:Configuration=Release

      - name: Prepare artifacts
        run: |
          mkdir release
          xcopy x64\Release\* release\ /E /I /Y

      - name: Generate tag
        id: tag
        run: echo "tag=release-${{ github.run_number }}" >> $env:GITHUB_OUTPUT

      - name: Create and push tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.tag.outputs.tag }}
          git push origin ${{ steps.tag.outputs.tag }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Generate changelog
        run:  |        
          export CI=true
          npx --yes changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: Release (v${{ github.run_number }})
          files: release/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}